version: "3"

services:
  db:
    image: postgres:9.6
    restart: always
    container_name: "message-board-db"
    ports:
      - 9999:80
    environment:
      - POSTGRES_DB=message_board
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
    volumes:
      - ./dump/pgsql:/docker-entrypoint-initdb.d
      - ./db/postgres:/var/lib/postgresql/data

  app:
    build: .
    container_name: "message-board-app"
    depends_on:
      - db
    environment:
      DB_ADDR: db
      DB_USER: example
      DB_PASS: example
      DB_TYPE: pgsql
    network_mode: service:db

  nginx:
    image: "nginx:latest"
    container_name: "message-board-nginx"
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/etc/nginx/html/static:ro
    depends_on:
      - app
    network_mode: service:app
