version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: "message-board-db"
    ports:
      - "9999:80"
    environment:
      MYSQL_DATABASE: message_board
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    volumes:
      - ./dump:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: "message-board-app"
    depends_on:
      - db
    environment:
      DB_ADDR: db
      DB_USER: example
      DB_PASS: example
      DB_TYPE: mysql
    network_mode: service:db

  nginx:
    image: "nginx:latest"
    container_name: "message-board-nginx"
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/etc/nginx/html/static:ro
    depends_on:
      - app
    network_mode: service:app
