version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: "message-board-db"
    environment:
      MYSQL_DATABASE: message_board
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - message-board-network

  app:
    build: .
    container_name: "message-board-app"
    depends_on:
      - db
    networks:
      - message-board-network
    environment:
      DB_ADDR: db
      DB_USER: example
      DB_PASS: example
      DB_TYPE: mysql

  nginx:
    image: "nginx:latest"
    container_name: "message-board-nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/etc/nginx/html/static:ro
    networks:
      - message-board-network
    depends_on:
      - app

networks:
  message-board-network:
